### ISSUE TITLE
Clone isnt work 

### ISSUE THREAD

**Issue by abdiasriver** [breakdowns/slam-mirrorbot#253]
2021-07-03T05:53:18.995660+00:00 app[worker.1]: 2021-07-03 05:53:18,995 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 0.json service account
2021-07-03T05:53:19.058256+00:00 app[worker.1]: Exception in thread Thread-2:
2021-07-03T05:53:19.058268+00:00 app[worker.1]: Traceback (most recent call last):
2021-07-03T05:53:19.058268+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2021-07-03T05:53:19.058906+00:00 app[worker.1]:     self.run()
2021-07-03T05:53:19.058911+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/threading.py", line 892, in run
2021-07-03T05:53:19.059449+00:00 app[worker.1]:     self._target(*self._args, **self._kwargs)
2021-07-03T05:53:19.059450+00:00 app[worker.1]:   File "/usr/src/app/bot/modules/clone.py", line 23, in cloneNode
2021-07-03T05:53:19.059546+00:00 app[worker.1]:     result, button = gd.clone(link)
2021-07-03T05:53:19.059553+00:00 app[worker.1]: ValueError: too many values to unpack (expected 2)

**Comment by breakdowns** [comment]
Working fine here. Did u use latest commit?
![IMG_20210703_130156](https://user-images.githubusercontent.com/71178188/124344826-feec3080-dbfe-11eb-9963-e66c358a2120.jpg)

**Comment by breakdowns** [comment]
........

**Comment by anasty17** [comment]
Can u plz contact us on group https://t.me/SlamMirrorSupport
